#
# This overlay file is intended for deployment of shared resources across all non-production environments.
# Resources defined here will be available in all pseudo-environments (e.g., dev, staging, etc.) within the non-production namespace.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
nameSuffix: -shared
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: shared
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: shared
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/maintenance/
  - ../../base/squid-proxy/
patches:
  - path: ./patches/deployments.yaml
configMapGenerator:
  - name: squid-proxy
    files:
      - ./configs/squid-proxy/config.conf
