# @see https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    cooldown:
      default: 3          # Wait 3 days after a new version is published before opening a PR
      semver-major: 7      # Wait 7 days for major version bumps
      semver-minor: 5      # Wait 5 days for minor version bumps
    groups:
      dev-minor-versions:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - 'react-router'
          - '@react-router/*'
      prod-minor-versions:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - 'react-router'
          - '@react-router/*'
      react-router-versions:
        update-types:
          - minor
          - patch
        patterns:
          - 'react-router'
          - '@react-router/*'

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    # Ignore major updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: terraform
    directory: /infrastructure
    schedule:
      interval: weekly
      day: monday
