# @see https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-minor-versions:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - '@react-router/*'
      prod-minor-versions:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
        exclude-patterns:
          - '@react-router/*'
      react-router-versions:
        update-types:
          - minor
          - patch
        patterns:
          - '@react-router/*'

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: terraform
    directory: /infrastructure
    schedule:
      interval: weekly
      day: monday
