apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: squid-proxy
  template:
    spec:
      containers:
        - name: squid-proxy
          volumeMounts:
            - name: squid-proxy-conf
              mountPath: /etc/squid/conf.d/dshp.conf
              subPath: config.conf
      volumes:
        - name: squid-proxy-conf
          configMap:
            name: squid-proxy
