apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    # TODO :: GjB :: to be removed when the URLs in the application have been fixed
    nginx.ingress.kubernetes.io/server-snippet: |
      rewrite ^/fr/renouveler(.*)$ /fr/renouveller$1 redirect;
      rewrite ^/fr/protege/renouveler(.*)$ /fr/protege/renouveller$1 redirect;
spec:
  ingressClassName: nginx
  rules:
    - host: srv024.service.canada.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-internal
  labels:
    app.kubernetes.io/name: frontend
spec:
  ingressClassName: nginx
  rules:
    - host: canada-dental-care-plan.prod-dp-internal.dts-stn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http