apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-prod-sced-rhp-spoke-aks
      app.kubernetes.io/environment: prod
      app.kubernetes.io/tier: prod
resources:
  - ../../base/error-pages/404
  - ../../base/frontend/
  - ../../base/fluentd-archiver/
  - ../../base/maintenance/
  - ../../base/redis/
  - ./hpas.yaml
  #
  # Note: to enable maintenance mode:
  #
  #   1. comment ./ingresses.yaml
  #   2. uncomment the appropriate maintenance mode file:
  #      - for full application maintenance, uncomment ./ingresses-maintenance.yaml
  #      - for online application maintenance, uncomment ./ingresses-apply-maintenance.yaml
  #
  # For renewal application downtime with a 404 response, uncomment ./ingresses-renew-error-404.yaml
  #
  - ./ingresses.yaml
  # - ./ingresses-maintenance.yaml
  # - ./ingresses-apply-maintenance.yaml
  # Note: for the letters maintenance page, see the maintenance configMapGenerator below
  # - ./ingresses-letters-maintenance.yaml
  # - ./ingresses-renew-error-404.yaml
patches:
  - path: ./patches/deployments-error-404.yaml
  - path: ./patches/deployments-frontend.yaml
  - path: ./patches/deployments-maintenance.yaml
  - path: ./patches/pvcs.yaml
  - path: ./patches/services.yaml
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - name: frontend
    behavior: merge
    envs:
      - ./configs/frontend/config.conf
  - name: frontend-fluentd
    behavior: create
    files:
      - ./configs/frontend/fluentd.conf
  - name: redis
    behavior: merge
    files:
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
  - name: oauth-proxy
    behavior: create
    files:
      - ./configs/oauth-proxy/config.conf
  - name: maintenance
    behavior: merge
    # TODO :: GjB :: this is a temporary override of the maintenance page HTML
    #                it should be removed when the letters are brought back online
    # TODO :: GjB :: I am commenting this out but leaving the updated 503 page in
    #                the project as a reference for future, similar deployments
    # files:
    #   - ./configs/maintenance/503.html
    literals:
      - startTimeEn=10:00pm EDT April 30, 2025
      - startTimeFr=30 avril 2025 à 22 h 00 HAE
      - endTimeEn=7:00am EDT May 1, 2025
      - endTimeFr=1 mai 2025 à 7 h 00 HAE
secretGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend/secrets.conf
  - name: redis
    behavior: replace
    envs:
      - ./configs/redis/secrets.conf
  - name: oauth-proxy
    behavior: create
    envs:
      - ./configs/oauth-proxy/secrets.conf