apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-prod-sced-rhp-spoke-aks
      app.kubernetes.io/environment: prod
      app.kubernetes.io/tier: prod
resources:
  - ../../base/frontend/
  - ../../base/fluentd-archiver/
  - ../../base/maintenance/
  - ../../base/redis/
  - ./hpas.yaml
  #
  # Note: to enable maintenance mode:
  #
  #   1. comment ./ingresses.yaml
  #   2. uncomment the appropriate maintenance mode file:
  #      - for full application maintenance, uncomment ./ingresses-maintenance.yaml
  #      - for online application maintenance, uncomment ./ingresses-apply-maintenance.yaml
  #
  # - ./ingresses.yaml
  # - ./ingresses-maintenance.yaml
  - ./ingresses-apply-maintenance.yaml
patches:
  - path: ./patches/deployments-frontend.yaml
  - path: ./patches/deployments-maintenance.yaml
  - path: ./patches/pvcs.yaml
  - path: ./patches/services.yaml
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - name: frontend
    behavior: merge
    envs:
      - ./configs/frontend/config.conf
  - name: frontend-fluentd
    behavior: create
    files:
      - ./configs/frontend/fluentd.conf
  - name: redis
    behavior: merge
    files:
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
  - name: oauth-proxy
    behavior: create
    files:
      - ./configs/oauth-proxy/config.conf
  - name: maintenance
    behavior: merge
    literals:
      - startTimeEn=10:00pm EST December 6, 2024
      - startTimeFr=22 h 00 HNE le 6 décembre 2024
      - endTimeEn=10:00pm December 8, 2024
      - endTimeFr=22 h 00 le 8 décembre 2024
secretGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend/secrets.conf
  - name: redis
    behavior: replace
    envs:
      - ./configs/redis/secrets.conf
  - name: oauth-proxy
    behavior: create
    envs:
      - ./configs/oauth-proxy/secrets.conf