apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    # reload the pod whenever the secrets change
    secret.reloader.stakater.com/auto: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    spec:
      containers:
        - name: canada-dental-care-plan-frontend
          image: dtsrhpdevscedacr.azurecr.io/canada-dental-care-plan/canada-dental-care-plan-frontend:0.0.0-951fc35f
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend
            - secretRef:
                name: frontend
            - secretRef:
                name: redis
