apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    spec:
      containers:
        - name: canada-dental-care-plan-frontend
          image: dtsrhpdevscedacr.azurecr.io/canada-dental-care-plan/canada-dental-care-plan-frontend:feat-ui-2.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend
            - secretRef:
                name: frontend
