export const pageIds = {
  protected: {
    application: {
      index: 'CDCP-PROT-APPL-0001',
      eligibilityRequirements: 'CDCP-PROT-APPL-0002',
      typeOfApplication: 'CDCP-PROT-APPL-0003',
      intakeAdult: {
        maritalStatus: 'CDCP-PROT-APPL-FAD-0001',
        dentalInsurance: 'CDCP-PROT-APPL-FAD-0002',
        contactInformation: 'CDCP-PROT-APPL-FAD-0003',
        submit: 'CDCP-PROT-APPL-FAD-0004',
        confirmation: 'CDCP-PROT-APPL-FAD-0005',
        exitApplication: 'CDCP-PROT-APPL-FAD-0006',
      },
      intakeChild: {
        parentOrGuardian: 'CDCP-PROT-APPL-FCH-0001',
        submit: 'CDCP-PROT-APPL-FCH-0003',
        exitApplication: 'CDCP-PROT-APPL-FCH-0004',
        confirmation: 'CDCP-PROT-APPL-FCH-0005',
        childApplication: 'CDCP-PROT-APPL-FCH-0006',
      },
      intakeFamily: {
        maritalStatus: 'CDCP-PROT-APPL-FFAM-0001',
        contactInformation: 'CDCP-PROT-APPL-FFAM-0002',
        dentalInsurance: 'CDCP-PROT-APPL-FFAM-0003',
        submit: 'CDCP-PROT-APPL-FFAM-0004',
        confirmation: 'CDCP-PROT-APPL-FFAM-0005',
        childApplication: 'CDCP-PROT-APPL-FFAM-0006',
        exitApplication: 'CDCP-PROT-APPL-FFAM-0007',
      },
      renewalAdult: {
        maritalStatus: 'CDCP-PROT-APPL-SAD-0001',
        dentalInsurance: 'CDCP-PROT-APPL-SAD-0002',
        contactInformation: 'CDCP-PROT-APPL-SAD-0003',
        submit: 'CDCP-PROT-APPL-SAD-0004',
        confirmation: 'CDCP-PROT-APPL-SAD-0005',
        exitApplication: 'CDCP-PROT-APPL-SAD-0006',
      },
      renewalChild: {
        parentOrGuardian: 'CDCP-PROT-APPL-SCH-0001',
        submit: 'CDCP-PROT-APPL-SCH-0002',
        exitApplication: 'CDCP-PROT-APPL-SCH-0003',
        childApplication: 'CDCP-PROT-APPL-SCH-0004',
        confirmation: 'CDCP-PROT-APPL-SCH-0005',
      },
      renewalFamily: {
        maritalStatus: 'CDCP-PROT-APPL-SFAM-0001',
        contactInformation: 'CDCP-PROT-APPL-SFAM-0002',
        dentalInsurance: 'CDCP-PROT-APPL-SFAM-0003',
        childApplication: 'CDCP-PROT-APPL-SFAM-0004',
        submit: 'CDCP-PROT-APPL-SFAM-0005',
        confirmation: 'CDCP-PROT-APPL-SFAM-0006',
        exitApplication: 'CDCP-PROT-APPL-SFAM-0007',
      },
      spokes: {
        taxFiling: 'CDCP-PROT-APPL-SPK-0001',
        fileYourTaxes: 'CDCP-PROT-APPL-SPK-0002',
        typeOfApplication: 'CDCP-PROT-APPL-SPK-0003',
        applicationDelegate: 'CDCP-PROT-APPL-SPK-0004',
        personalInformation: 'CDCP-PROT-APPL-SPK-0005',
        livingIndependently: 'CDCP-PROT-APPL-SPK-0006',
        parentOrGuardian: 'CDCP-PROT-APPL-SPK-0007',
        maritalStatus: 'CDCP-PROT-APPL-SPK-0008',
        termsConditions: 'CDCP-PROT-APPL-SPK-0009',
        dentalInsurance: 'CDCP-PROT-APPL-SPK-0010',
        newOrReturningMember: 'CDCP-PROT-APPL-SPK-0011',
        confirmFederalProvincialTerritorialBenefits: 'CDCP-PROT-APPL-SPK-0012',
        federalProvincialTerritorialBenefits: 'CDCP-PROT-APPL-SPK-0013',
        phoneNumber: 'CDCP-PROT-APPL-SPK-0014',
        mailingAddress: 'CDCP-PROT-APPL-SPK-0015',
        homeAddress: 'CDCP-PROT-APPL-SPK-0016',
        communicationPreferences: 'CDCP-PROT-APPL-SPK-0017',
        email: 'CDCP-PROT-APPL-SPK-0018',
        verifyEmail: 'CDCP-PROT-APPL-SPK-0019',
        childInformation: 'CDCP-PROT-APPL-SPK-0020',
        childParentOrGuardian: 'CDCP-PROT-APPL-SPK-0021',
        cannotApplyChild: 'CDCP-PROT-APPL-SPK-0022',
        childDentalInsurance: 'CDCP-PROT-APPL-SPK-0023',
        childConfirmFederalProvincialTerritorialBenefits: 'CDCP-PROT-APPL-SPK-0024',
        childFederalProvincialTerritorialBenefits: 'CDCP-PROT-APPL-SPK-0025',
        dentalInsuranceExitApplication: 'CDCP-PROT-APPL-SPK-0026',
        renewalSelection: 'CDCP-PROT-APPL-SPK-0027',
        parentGuardian: 'CDCP-PROT-APPL-SPK-0028',
        childSocialInsuranceNumber: 'CDCP-PROT-APPL-SPK-0029',
        cannotApplyChildYear: 'CDCP-PROT-APPL-SPK-0030',
      },
    },
    documents: {
      index: 'CDCP-PROT-DOCS-0001',
      upload: 'CDCP-PROT-DOCS-0002',
      notRequired: 'CDCP-PROT-DOCS-0003',
    },
    letters: {
      index: 'CDCP-PROT-0015',
    },
    dataUnavailable: 'CDCP-PROT-0099',
    unableToProcessRequest: 'CDCP-PROT-0999',
    profile: {
      eligibility: 'CDCP-PROT-PROF-0001',
      applicantInformation: 'CDCP-PROT-PROF-0002',
      dentalBenefits: 'CDCP-PROT-PROF-0003',
      communicationPreferences: 'CDCP-PROT-PROF-0004',
      editCommunicationPreferences: 'CDCP-PROT-PROF-0005',
      phoneNumber: 'CDCP-PROT-PROF-0006',
      contactInformation: 'CDCP-PROT-PROF-0007',
      email: 'CDCP-PROT-PROF-0008',
      verifyEmail: 'CDCP-PROT-PROF-0009',
      editDentalBenefits: 'CDCP-PROT-PROF-0010',
      editChildDentalBenefits: 'CDCP-PROT-PROF-0011',
      editMailingAddress: 'CDCP-PROT-PROF-0012',
      editHomeAddress: 'CDCP-PROT-PROF-0013',
    },
  },
  public: {
    application: {
      index: 'CDCP-APPL-0001',
      eligibilityRequirements: 'CDCP-APPL-0002',
      typeOfApplication: 'CDCP-APPL-0003',
      fullAdult: {
        maritalStatus: 'CDCP-APPL-FAD-0001',
        dentalInsurance: 'CDCP-APPL-FAD-0002',
        contactInformation: 'CDCP-APPL-FAD-0003',
        submit: 'CDCP-APPL-FAD-0004',
        confirmation: 'CDCP-APPL-FAD-0005',
        exitApplication: 'CDCP-APPL-FAD-0006',
      },
      fullChild: {
        parentOrGuardian: 'CDCP-APPL-FCH-0001',
        submit: 'CDCP-APPL-FCH-0003',
        exitApplication: 'CDCP-APPL-FCH-0004',
        confirmation: 'CDCP-APPL-FCH-0005',
        childApplication: 'CDCP-APPL-FCH-0006',
      },
      fullFamily: {
        maritalStatus: 'CDCP-APPL-FFAM-0001',
        contactInformation: 'CDCP-APPL-FFAM-0002',
        dentalInsurance: 'CDCP-APPL-FFAM-0003',
        submit: 'CDCP-APPL-FFAM-0004',
        confirmation: 'CDCP-APPL-FFAM-0005',
        childApplication: 'CDCP-APPL-FFAM-0006',
        exitApplication: 'CDCP-APPL-FFAM-0007',
      },
      simplifiedAdult: {
        contactInformation: 'CDCP-APPL-SAD-0001',
        dentalInsurance: 'CDCP-APPL-SAD-0002',
        submit: 'CDCP-APPL-SAD-0003',
        confirmation: 'CDCP-APPL-SAD-0004',
        exitApplication: 'CDCP-APPL-SAD-0005',
      },
      simplifiedChild: {
        parentOrGuardian: 'CDCP-APPL-SCH-0001',
        submit: 'CDCP-APPL-SCH-0002',
        exitApplication: 'CDCP-APPL-SCH-0003',
        childApplication: 'CDCP-APPL-SCH-0004',
        confirmation: 'CDCP-APPL-SCH-0005',
      },
      simplifiedFamily: {
        contactInformation: 'CDCP-APPL-SFAM-0001',
        dentalInsurance: 'CDCP-APPL-SFAM-0002',
        childApplication: 'CDCP-APPL-SFAM-0003',
        submit: 'CDCP-APPL-SFAM-0004',
        confirmation: 'CDCP-APPL-SFAM-0005',
        exitApplication: 'CDCP-APPL-SFAM-0006',
      },
      spokes: {
        taxFiling: 'CDCP-APPL-SPK-0001',
        fileYourTaxes: 'CDCP-APPL-SPK-0002',
        typeOfApplication: 'CDCP-APPL-SPK-0003',
        applicationDelegate: 'CDCP-APPL-SPK-0004',
        personalInformation: 'CDCP-APPL-SPK-0005',
        livingIndependently: 'CDCP-APPL-SPK-0006',
        parentOrGuardian: 'CDCP-APPL-SPK-0007',
        maritalStatus: 'CDCP-APPL-SPK-0008',
        termsConditions: 'CDCP-APPL-SPK-0009',
        dentalInsurance: 'CDCP-APPL-SPK-0010',
        newOrReturningMember: 'CDCP-APPL-SPK-0011',
        confirmFederalProvincialTerritorialBenefits: 'CDCP-APPL-SPK-0012',
        federalProvincialTerritorialBenefits: 'CDCP-APPL-SPK-0013',
        phoneNumber: 'CDCP-APPL-SPK-0014',
        mailingAddress: 'CDCP-APPL-SPK-0015',
        homeAddress: 'CDCP-APPL-SPK-0016',
        communicationPreferences: 'CDCP-APPL-SPK-0017',
        email: 'CDCP-APPL-SPK-0018',
        verifyEmail: 'CDCP-APPL-SPK-0019',
        childInformation: 'CDCP-APPL-SPK-0020',
        childParentOrGuardian: 'CDCP-APPL-SPK-0021',
        cannotApplyChild: 'CDCP-APPL-SPK-0022',
        childDentalInsurance: 'CDCP-APPL-SPK-0023',
        childConfirmFederalProvincialTerritorialBenefits: 'CDCP-APPL-SPK-0024',
        childFederalProvincialTerritorialBenefits: 'CDCP-APPL-SPK-0025',
        dentalInsuranceExitApplication: 'CDCP-APPL-SPK-0026',
      },
    },
    status: {
      index: 'CDCP-STAT-0001',
      myself: 'CDCP-STAT-0002',
      child: 'CDCP-STAT-0003',
      result: 'CDCP-STAT-0004',
    },
    unableToProcessRequest: 'CDCP-UNAB-0001',
    notFound: 'CDCP-ERR-0404',
  },
} as const;
