apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    spec:
      containers:
        - name: canada-dental-care-plan-frontend
          image: dtsrhpdevscedacr.azurecr.io/canada-dental-care-plan/canada-dental-care-plan-frontend:0.0.0-ea4c58b8-0062c
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: frontend
            - secretRef:
                name: frontend
            - secretRef:
                name: redis
        - name: oauth-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --config=/etc/oauth-proxy.conf
          envFrom:
            - secretRef:
                name: oauth-proxy
          ports:
            - name: oauth-proxy
              containerPort: 4180
          livenessProbe:
            httpGet:
              path: /ping
              port: oauth-proxy
            initialDelaySeconds: 0
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: oauth-proxy
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: oauth-proxy-conf
              mountPath: /etc/oauth-proxy.conf
              subPath: config.conf
        - name: fluentd
          image: docker.io/fluentd
          args: [--config, /etc/fluentd.conf]
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: audit-logs
              mountPath: /logs
            - name: fluentd-conf
              mountPath: /etc/fluentd.conf
              subPath: fluentd.conf
      volumes:
        - name: fluentd-conf
          configMap:
            name: frontend-fluentd
        - name: oauth-proxy-conf
          configMap:
            name: oauth-proxy
