apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
resources:
  - ./services.yaml
  - ./stateful-sets.yaml
configMapGenerator:
  - name: redis
    files:
      - ./configs/config.conf
secretGenerator:
  - name: redis
    envs:
      - ./configs/secrets.conf