apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: sentinel
      port: 26379
      targetPort: 26379
  selector:
    app.kubernetes.io/name: redis

---

#
# The headless service is used by sentinel to target individual pods
#
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app.kubernetes.io/name: redis-headless
spec:
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: sentinel
      port: 26379
      targetPort: 26379
  selector:
    app.kubernetes.io/name: redis