apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  labels:
    app.kubernetes.io/name: maintenance
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: maintenance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maintenance
    spec:
      containers:
        - name: nginx
          # Note: image tag should be pinned to a specific version in overlays
          image: docker.io/nginx:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: maintenance-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: config.conf
            - name: maintenance-conf
              mountPath: /usr/share/nginx/html/503.html
              subPath: 503.html
      volumes:
        - name: maintenance-conf
          configMap:
            name: maintenance