apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
resources:
  - ./deployments.yaml
  - ./services.yaml
configMapGenerator:
  - name: maintenance
    files:
      - ./configs/503.html
      - ./configs/config.conf
