apiVersion: v1
kind: Service
metadata:
  name: maintenance
  labels:
    app.kubernetes.io/name: maintenance
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: maintenance