trigger:
  - ado-prototype-deployment

pr: none

variables:
  azureContainerRegistry.repository: canadian-dental-care-plan/frontend
  azureContainerRegistry.name: dtsshared-04/29/24
  azureContainerRegistry.domain: dtsshared.azurecr.io
  vmImageName: ubuntu-latest
  image.shortHash: ''
  image.tag: prototype-candidate

stages:
  - stage: Build
    displayName: Build and Push to ACR
    jobs:
      - job: Build
        displayName: Build and Push Container
        pool:
          vmImage: $(vmImageName)
        steps:
          - bash: |
              short_hash=`git rev-parse --short=7 HEAD`
              echo ""
              echo "Full git hash:  $(Build.SourceVersion)"
              echo "Short git hash: $short_hash"
              echo "##vso[task.setvariable variable=image.shortHash]$short_hash"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: Get short git hash

          - task: Docker@2
            inputs:
              containerRegistry: $(azureContainerRegistry.name)
              repository: $(azureContainerRegistry.repository)
              command: login
          - script: docker pull $(azureContainerRegistry.domain)/$(azureContainerRegistry.repository):latest
            displayName: Pull latest for layer caching
            continueOnError: true
          - task: Docker@2
            inputs:
              containerRegistry: $(azureContainerRegistry.name)
              repository: $(azureContainerRegistry.repository)
              command: buildAndPush
              Dockerfile: ./frontend/dockerfile
              tags: |
                $(image.shortHash)
                $(image.tag)
                latest
              arguments: |
                --pull
                