apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-404
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: error-404
  template:
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:1.27.0