apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 3
  serviceName: redis-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    #
    # pin all versions to v8.8.0
    #
    spec:
      initContainers:
        - name: init
          image: docker.io/redis:8.8.0
      containers:
        - name: redis
          image: docker.io/redis:8.8.0
        - name: redis-sentinel
          image: docker.io/redis:8.8.0