apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
nameSuffix: -ui20
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: ui20
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: ui20
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/frontend/
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments.yaml
configMapGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend-config.conf
secretGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend-secrets.conf
