apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
nameSuffix: -int
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: int
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: int
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/frontend/
  - ../../base/redis/
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments.yaml
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend-config.conf
  - name: redis
    behavior: replace
    files:
      - ./configs/redis-config.conf
secretGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend-secrets.conf
  - name: redis
    behavior: replace
    envs:
      - ./configs/redis-secrets.conf