apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
labels:
  - includeTemplates: true
    pairs:
      app.kubernetes.io/name: postgres-operator
      # The version below should match the version on the PostgresCluster CRD
      app.kubernetes.io/version: 5.6.0
      postgres-operator.crunchydata.com/control-plane: postgres-operator

resources:
  - ./manager.yaml
  - ./role_binding.yaml
  - ./role.yaml
  - ./service_account.yaml

images:
  - name: postgres-operator
    newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
    newTag: ubi8-5.6.0-0

patches:
  - path: manager-target.yaml
