apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
  labels:
    app.kubernetes.io/name: squid-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: squid-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid-proxy
    spec:
      containers:
        - name: squid-proxy
          # Note: image tag should be pinned to a specific version in overlays
          image: docker.io/ubuntu/squid:latest
          ports:
            - name: squid
              containerPort: 3128
          livenessProbe:
            exec:
              command: [/usr/sbin/squid, -k, parse]
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command: [/usr/sbin/squid, -k, parse]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
