apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-proxy
  labels:
    app.kubernetes.io/name: squid-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: squid-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: squid-proxy
    spec:
      containers:
        - name: squid-proxy
          # Note: image tag should be pinned to a specific version in overlays
          image: docker.io/ubuntu/squid:latest
          ports:
            - name: squid
              containerPort: 3128
          livenessProbe:
            tcpSocket:
              port: squid
          readinessProbe:
            tcpSocket:
              port: squid
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
