apiVersion: v1
kind: Service
metadata:
  name: squid-proxy
  labels:
    app.kubernetes.io/name: squid-proxy
spec:
  selector:
    app.kubernetes.io/name: squid-proxy
  ports:
    - name: squid
      port: 3128
      targetPort: squid
