#
# Spring Boot configuration properties. For a full listing of available properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties
#

---

logging:
  level:
    '[ca.gov.dtsstn.cdcp.api]': info

---

spring:
  application:
    name: Canadian Dental Care Plan API
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 20
  devtools:
    livereload:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:test;COLLATION=ENGLISH STRENGTH PRIMARY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;MODE=PostgreSQL
    hikari: # see https://github.com/brettwooldridge/HikariCP#frequently-used
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  flyway: # see org.springframework.boot.autoconfigure.flyway.FlwayProperties
    locations: classpath:db-migrations/common, classpath:db-migrations/{vendor}
    sql-migration-prefix: v
    sql-migration-separator: '-'
  jackson:
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      '[hibernate.batch_versioned_data]': true
      '[hibernate.globally_quoted_identifiers]': true
      '[hibernate.jdbc.batch_size]': 100
      '[hibernate.order_inserts]': true
      '[hibernate.order_updates]': true

---

#
# Actuator configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.actuator
#

management:
  endpoint:
    env:
      show-values: when-authorized
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized

---

#
# Server configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.server
#

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  shutdown: graceful

---

#
# Application configuration properties.
#

application:
  caching:
    enabled: true
    caches:
      alert-types:
        # cache alert types for one minute to
        # reduce excessive database calls
        expire-after-write: 1
        time-unit: minutes
  swagger-ui:
    application-name: Canadian Dental Care Plan API
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/canadian-dental-care-plan/
    description: |
      This OpenAPI document describes the key areas where developers typically engage with this API.
    tos-url: https://www.canada.ca/en/transparency/terms.html
