#
# Spring Boot configuration properties. For a full listing of available properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties
#

---

spring:
  application:
    name: Canadian Dental Care Plan API
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 500
  devtools:
    livereload:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: # must set externally
    hikari: # see https://github.com/brettwooldridge/HikariCP#frequently-used
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  flyway: # see org.springframework.boot.autoconfigure.flyway.FlwayProperties
    sql-migration-prefix: v
    sql-migration-separator: '-'
    locations: classpath:db-migrations/common, classpath:db-migrations/{vendor}
  jackson:
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate

---

#
# Actuator configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.actuator
#

management:
  endpoint:
    env:
      show-values: when-authorized
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized

---

#
# Server configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.server
#

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  shutdown: graceful

---

#
# Application configuration properties.
#

application:
  swagger-ui:
    application-name: Canadian Dental Care Plan API
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/canadian-dental-care-plan/
    description: |
      This OpenAPI document describes the key areas where developers typically engage with this API.
    tos-url: https://www.canada.ca/en/transparency/terms.html
