#
# Spring Boot configuration properties. For a full listing of available properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties
#

---

logging:
  level:
    '[ca.gov.dtsstn.cdcp.api]': info

---

spring:
  application:
    name: Canadian Dental Care Plan API
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 20
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:test;COLLATION=ENGLISH STRENGTH PRIMARY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;MODE=PostgreSQL
    hikari: # see https://github.com/brettwooldridge/HikariCP#frequently-used
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
  devtools:
    livereload:
      enabled: false
  flyway: # see org.springframework.boot.autoconfigure.flyway.FlwayProperties
    locations: classpath:db-migrations/common, classpath:db-migrations/{vendor}
    sql-migration-prefix: v
    sql-migration-separator: '-'
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    default-property-inclusion: non-null
    mapper:
      default-view-inclusion: true
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      '[hibernate.batch_versioned_data]': true
      '[hibernate.globally_quoted_identifiers]': true
      '[hibernate.jdbc.batch_size]': 100
      '[hibernate.order_inserts]': true
      '[hibernate.order_updates]': true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      #
      # ⚠️ Spring Security's resource server settings must be configured
      # externally when `application.security.enabled` is set to `true`
      #
      resourceserver:
        jwt:
          audiences: 00000000-0000-0000-0000-000000000000
          issuer-uri: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0
          jwk-set-uri: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/discovery/v2.0/keys

---

#
# Actuator configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.actuator
#

management:
  endpoint:
    env:
      show-values: when-authorized
    health:
      probes:
        enabled: true
      show-components: always
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include:
        - metrics

---

#
# Server configuration properties, see:
# https://docs.spring.io/spring-boot/docs/3.2.x/reference/html/application-properties.html#appendix.application-properties.server
#

server:
  compression:
    enabled: true
    mime-types:
      - application/hal+json
      # defaults below...
      - application/javascript
      - application/json
      - application/xml
      - text/css
      - text/html
      - text/javascript
      - text/plain
      - text/xml
  error:
    include-stacktrace: never
  shutdown: graceful

---

springdoc:
  swagger-ui:
    #
    # ⚠️ SpringDoc OAuth settings must be configured externally
    # when `application.security.enabled` is set to `true`
    #
    oauth:
      client-id: api://api.example.com
      scopes: api://api.example.com/.default

---

#
# Application configuration properties.
#

application:
  caching:
    enabled: true
    caches:
      alert-types:
        # cache alert types for one minute to
        # reduce excessive database calls
        expire-after-write: 1
        time-unit: minutes
      languages:
        # cache preferred languages for one minute to
        # reduce excessive database calls
        expire-after-write: 1
        time-unit: minutes
  email-notifications:
    confirmation-codes:
      expiry:
        value: 24
        time-unit: hours
      length: 5
  swagger-ui:
    application-name: Canadian Dental Care Plan API
    contact-name: Digital Technology Solutions
    contact-url: https://github.com/dts-stn/canadian-dental-care-plan/
    description: This OpenAPI document describes the key areas where developers typically engage with this API.
    tos-url: https://www.canada.ca/en/transparency/terms.html
    #
    # ⚠️ Swagger UI authentication settings must be configured
    # externally when `application.security.enabled` is set to `true`
    #
    authentication:
      client-id: api://api.example.com
      authorization-url: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/authorize
      token-url: https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/oauth2/v2.0/token
