apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
nameSuffix: -int1
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/instance: int1
labels:
  - pairs:
      app.kubernetes.io/part-of: canada-dental-care-plan
      app.kubernetes.io/managed-by: teamcity
      app.kubernetes.io/cluster: dts-dev-sced-rhp-spoke-aks
      app.kubernetes.io/environment: int1
      app.kubernetes.io/tier: nonprod
resources:
  - ../../base/frontend/
  - ../../base/fluentd-archiver/
  - ../../base/redis/
  - ./ingresses.yaml
patches:
  - path: ./patches/deployments.yaml
  - path: ./patches/services.yaml
  - path: ./patches/stateful-sets.yaml
configMapGenerator:
  - name: frontend
    behavior: merge
    envs:
      - ./configs/frontend/config.conf
  - name: frontend-fluentd
    behavior: create
    files:
      - ./configs/frontend/fluentd.conf
  - name: redis
    behavior: merge
    files:
      - ./configs/redis/replica.conf
      - ./configs/redis/sentinel.conf
  - name: oauth-proxy
    behavior: create
    files:
      - ./configs/oauth-proxy/config.conf
secretGenerator:
  - name: frontend
    behavior: replace
    envs:
      - ./configs/frontend/secrets.conf
  - name: oauth-proxy
    behavior: create
    envs:
      - ./configs/oauth-proxy/secrets.conf
  - name: redis
    behavior: replace
    envs:
      - ./configs/redis/secrets.conf