apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-archiver
  labels:
    app.kubernetes.io/name: fluentd-archiver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd-archiver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentd-archiver
    spec:
      containers:
        - name: fluentd-archiver
          image: docker.io/fluentd
          args: [--config, /etc/fluentd.conf]
          ports:
            - name: fluentd
              containerPort: 24224
          volumeMounts:
            - name: audit-logs
              mountPath: /logs
            - name: fluentd-conf
              mountPath: /etc/fluentd.conf
              subPath: fluentd.conf
      securityContext:
        fsGroup: 101 # `fluent` gid
      volumes:
        - name: audit-logs
          persistentVolumeClaim:
            claimName: audit-logs
        - name: fluentd-conf
          configMap:
            name: fluentd-archiver