apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canada-dental-care-plan
resources:
  - ./deployments.yaml
  - ./pvcs.yaml
  - ./services.yaml
configMapGenerator:
  - name: fluentd-archiver
    files:
      - ./configs/fluentd.conf