apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-logs
  labels:
    app.kubernetes.io/name: audit-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi