apiVersion: v1
kind: Service
metadata:
  name: error-404
  labels:
    app.kubernetes.io/name: error-404
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: error-404