name: Build and test solution
permissions: read-all

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**
  workflow_call: {}
  workflow_dispatch: {}

env:
  CI: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'DTS-STN/canadian-dental-care-plan' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - id: frontend
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            src:
              - frontend/**
      - id: gitops
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            src:
              - gitops/**
      - id: infrastructure
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: |
            src:
              - infrastructure/**
    outputs:
      frontend-changed: ${{ steps.frontend.outputs.src }}
      gitops-changed: ${{ steps.gitops.outputs.src }}
      infrastructure-changed: ${{ steps.infrastructure.outputs.src }}

  test-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26.x
      - run: npm clean-install
        working-directory: frontend/
      - run: npm run format:check
        working-directory: frontend/
      - run: npm run typecheck
        working-directory: frontend/
      - run: npm run lint:eslint
        working-directory: frontend/
      - run: npm run test:unit:coverage
        working-directory: frontend/
      - run: npm run build
        working-directory: frontend/
      - run: npx playwright install chromium --with-deps
        working-directory: frontend/
      - run: npm run test:e2e:smoke
        working-directory: frontend/
  build-frontend:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend-changed == 'true' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26.x
      - run: npm clean-install
        working-directory: frontend/
      - run: podman build --file dockerfile .
        working-directory: frontend/
