name: Nightly e2e tests (main & release)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

env:
  CI: true

permissions: read-all

jobs:
  run-e2e-tests:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26.x
      - run: npm clean-install
        working-directory: frontend/
      - run: npm run build
        working-directory: frontend/
      - run: npx playwright install chromium --with-deps
        working-directory: frontend/
      - run: npm run test:e2e
        working-directory: frontend/